type: web

    name: webdis

    env: docker

    repo: https://github.com/ZDARKSHADOWXD/railway-ssh # optional

    region: oregon # optional (defaults to oregon)

    plan: standard # optional (defaults to starter)

    branch: main # optional (defaults to master)

    rootDir: webdis

    dockerCommand: ./1.sh # optional (defaults to Dockerfile command)

    numInstances: 1 #
